import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule, MatCardModule, MatDialogModule, MatInputModule, MatTableModule, MatSortModule, MatFormFieldModule,
  MatToolbarModule, MatMenuModule, MatIconModule, MatProgressSpinnerModule, MatSidenavModule, MatCheckboxModule,
  MatTooltipModule, MatSelectModule, MatSnackBarModule, MatListModule, MatPaginatorModule, MatExpansionModule,
  MatDatepickerModule, MatNativeDateModule, MatProgressBarModule, MatDividerModule, MatTabsModule, MatRadioModule,
  MatBadgeModule, MatChipsModule, MatRippleModule, MatStepperModule
} from '@angular/material';
@NgModule({
  imports: [
  CommonModule,
  MatToolbarModule,
  MatButtonModule,
  MatCardModule,
  MatInputModule,
  MatDialogModule,
  MatTableModule,
  MatMenuModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatSidenavModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatSortModule,
  MatTooltipModule,
  MatSelectModule,
  MatSnackBarModule,
  MatListModule,
  MatPaginatorModule,
  MatExpansionModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatProgressBarModule,
  MatDividerModule,
  MatTabsModule,
  MatRadioModule,
  MatBadgeModule,
  MatChipsModule,
  MatRippleModule,
  MatStepperModule
  ],
  exports: [
  CommonModule,
   MatToolbarModule,
   MatButtonModule,
   MatCardModule,
   MatInputModule,
   MatDialogModule,
   MatTableModule,
   MatMenuModule,
   MatIconModule,
   MatProgressSpinnerModule,
   MatSidenavModule,
   MatCheckboxModule,
   MatFormFieldModule,
   MatSortModule,
   MatSnackBarModule,
   MatTooltipModule,
   MatSelectModule,
   MatListModule,
   MatPaginatorModule,
   MatExpansionModule,
   MatDatepickerModule,
   MatProgressBarModule,
   MatDividerModule,
   MatTabsModule,
   MatRadioModule,
   MatBadgeModule,
   MatChipsModule,
   MatRippleModule,
   MatStepperModule
   ],
})
export class CustomMaterialModule { }
